name: textfield_manager
description: This package makes it easier to manage the state of textfields.
version: 1.0.0
repository: https://github.com/MasahideMori-SimpleAppli/textfield_namager

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
